config/routes.rb
Journal::Engine.routes.draw do
  mount VaultCore::Engine => '/'

  resources :journals
end

app/models/journal/application_record.rb
module Journal
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/journal/journal.rb
module Journal
  class Journal < ApplicationRecord
    self.table_name = 'journals'

    belongs_to :user, class_name: 'VaultCore::User'

    has_rich_text :content

    validates :title, :content, :date, presence: true
  end
end

app/controllers/journal/application_controller.rb
module Journal
  class ApplicationController < VaultCore::ApplicationController
  end
end

app/controllers/journal/journals_controller.rb
module Journal
  class JournalsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_journal, only: %i[show edit update destroy]

    def index
      @journal = user_journals.new
      @journals = user_journals.order(created_at: :desc)
      @pagy, @journals = pagy_countless(@journals)
    end

    def show; end

    def new
      @journal = user_journals.new
    end

    def create
      @journal = user_journals.new(journal_params)
      if @journal.save
        redirect_to journals_path
      else
        render :new
      end
    end

    def edit; end

    def update
      if @journal.update(journal_params)
        redirect_to journals_path
      else
        render :edit
      end
    end

    def destroy
      redirect_to journals_path if @journal.destroy
    end

    private

    def journal_params
      params.require(:journal).permit(:title, :content, :date)
    end

    def user_journals
      current_user.journals
    end

    def find_journal
      @journal = user_journals.find_by(id: params[:id])
    end
  end
end

app/helpers/journal/application_helper.rb
module Journal
  module ApplicationHelper
  end
end

app/helpers/journal/journals_helper.rb
module Journal
  module JournalsHelper
  end
end

app/views/journal/journals/_form.html.erb
<% if @journal.errors.present? %>
  <p>
    <% @journal.errors.full_messages.each do |e| %>
      <%= e %>
    <% end %>
  </p>
<% end %>

<%= form_with(model: @journal, class: 'mt-3') do |f| %>
  <div class="row mb-3">
    <%= f.label :title, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>
  <div class="row mb-3">
    <%= f.label :content, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.rich_text_area :content %>
    </div>
  </div>
  <div class="row mb-3">
    <%= f.label :date, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.date_field :date, class: 'form-control', max: Date.current %>
    </div>
  </div>
  <%= f.submit 'Save entry', class: 'btn btn-primary' %>
<% end %>

app/views/journal/journals/edit.html.erb
<div class="container">
  <%= render 'journal/journals/form' %>
</div>

app/views/journal/journals/index.html.erb
<main class="container">
  <div class="row g-5">
    <div class="col-md-8">
      <div class="pb-4 mb-4 border-bottom">
        <%= render 'journal/journals/form' %>
      </div>
      <% @journals.each do |journal| %>
        <article class="blog-post border-bottom">
          <h2 class="blog-post-title"><%= journal.title %></h2>
          <p class="blog-post-meta"><%= journal.date.strftime('%b %d, %Y') %></p>

          <%= journal.content %>

          <%= link_to 'Edit', edit_journal_path(journal) %>
          <%= link_to 'Delete', journal_path(journal), data: { 'turbo-method': :delete } %>

        </article>
      <% end %>


      <nav class="blog-pagination" aria-label="Pagination">
        <% if @pagy.pages > 1 %>
          <%== render partial: 'pagy/vault_core/bootstrap_nav', locals: {pagy: @pagy} %>
      <% end %>
      </nav>

    </div>

    <div class="col-md-4">
      <div class="position-sticky" style="top: 2rem;">

        <div class="p-4">
          <h4 class="fst-italic">Archives</h4>
          <ol class="list-unstyled mb-0">
            <li><a href="#">March 2021</a></li>
            <li><a href="#">February 2021</a></li>
            <li><a href="#">January 2021</a></li>
            <li><a href="#">December 2020</a></li>
            <li><a href="#">November 2020</a></li>
            <li><a href="#">October 2020</a></li>
            <li><a href="#">September 2020</a></li>
            <li><a href="#">August 2020</a></li>
            <li><a href="#">July 2020</a></li>
            <li><a href="#">June 2020</a></li>
            <li><a href="#">May 2020</a></li>
            <li><a href="#">April 2020</a></li>
          </ol>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/journal/journals/new.html.erb
<div class="container">
  <%= render 'journal/journals/form' %>
</div>

app/views/layouts/journal/application.html.erb
<%= render 'layouts/vault_core/application_layout', title: { label: 'Journal', url: '/journals'}, left_side_link: { label: 'New Journal', url: new_journal_path } do %>
 <%= yield %>
<% end %>